/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { Dropdown as ButtonDropdown } from './components/button-dropdown/button-dropdown';

interface HTMLButtonDropdownElement extends ButtonDropdown, HTMLElement {
}
declare var HTMLButtonDropdownElement: {
  prototype: HTMLButtonDropdownElement;
  new (): HTMLButtonDropdownElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "button-dropdown": HTMLButtonDropdownElement;
  }
  interface ElementTagNameMap {
      "button-dropdown": HTMLButtonDropdownElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "button-dropdown": JSXElements.ButtonDropdownAttributes;
      }
  }
  namespace JSXElements {
      export interface ButtonDropdownAttributes extends HTMLAttributes {
        
          title?: string
      }
  }
}

import { MyName as MyName } from './components/my-name/my-name';

interface HTMLMyNameElement extends MyName, HTMLElement {
}
declare var HTMLMyNameElement: {
  prototype: HTMLMyNameElement;
  new (): HTMLMyNameElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-name": HTMLMyNameElement;
  }
  interface ElementTagNameMap {
      "my-name": HTMLMyNameElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-name": JSXElements.MyNameAttributes;
      }
  }
  namespace JSXElements {
      export interface MyNameAttributes extends HTMLAttributes {
        
          first?: string,
          last?: string
      }
  }
}

